### ISSUE TITLE
Breaks admin-ajax.php functionality sometimes needed on the frontend for users whose dashboard access is disabled

### ISSUE THREAD

**Issue by romci** [ProfilePress/Admin-Bar-Dashboard-Control#1]
Recommended quick fix:

admin-bar-dashboard-control.php, add to function dashboard_access():

`if ( defined( 'DOING_AJAX' ) && DOING_AJAX ) {
  return;
}
`

(otherwise, great little plugin, does the job perfectly :)

**Comment by collizo4sky** [comment]
Can you please submit a pull request on this?

**Comment by collizo4sky** [comment]
Released. Thanks.
