### ISSUE TITLE
blank page, and dashboard still shows (multisite)

### ISSUE THREAD

**Issue by YesThatAllen** [ProfilePress/Admin-Bar-Dashboard-Control#3]
I just tried this plugin on my wordpress multisite running 4.5.3.

When I make a settings change, the admin view shows just a grey page. Refreshing the page displays the plugin again, and the changes appear to be saved.

Changes to the `Admin Bar` work, but only if `Disable Admin Bar` is selected. Is that expected?

Changes to `Dashboard Access` aren't being applied to the `Subscriber` Group we have.

Is there something about the settings I've done wrong, or is there some other information I can use to see what the problems are?

![screenshot_1763](https://cloud.githubusercontent.com/assets/2879972/16550452/5f714ca8-4170-11e6-95cf-97d8deb5051f.png)

**Comment by collizo4sky** [comment]
Hi, sorry for the late response. `Disable Admin Bar` is a global settings in that if unchecked, admin bar will still be visible.

The dashboard access control restrict access to the dashboard to certain roles.

I haven't tested the plugin with multisite.

Could you please give a detail step in how i can replicate this so i can fix the problem you having?

**Comment by collizo4sky** [comment]
Version 1.0.3 apparently fixes this issue. Update.
